### ISSUE TITLE
Option Not To Calc R^2 and SE

### ISSUE THREAD

**Issue by iwelch** [jasonjfoster/roll#47]
Because the primary purpose of this package is to be much more efficient, in cases where information other than coefficients are not needed, it would make sense not to calculate them...

**Comment by jasonjfoster** [comment]
Thanks for the suggestion. I tested a version of the `roll_lm` function that calculates only the coefficients that excludes r-squareds and standard errors. Benchmark results show that the runtime is nearly identical because these metrics reuse the coefficients and require minimal additional computation. You can find the modified code [here](https://github.com/user-attachments/files/17838297/roll_lm_z.zip).

```{r}
n_vars <- 100
n_obs <- 10000
width <- 100
weights <- rep(1, width)

x <- matrix(rnorm(n_obs * n_vars), nrow = n_obs, ncol = n_vars)
y <- matrix(rnorm(n_obs), nrow = n_obs, ncol = 1)

> microbenchmark::microbenchmark(
+   `roll` = roll_lm_z(x, y, width, weights, TRUE, 1, TRUE, TRUE),
+   `roll_coef` = roll_lm_coef_z(x, y, width, weights, TRUE, 1, TRUE, TRUE)
+ )
Unit: seconds
      expr      min       lq     mean   median       uq      max neval
      roll 1.779521 1.863692 1.883637 1.882911 1.898013 2.047160   100
 roll_coef 1.806635 1.859662 1.879181 1.873921 1.894191 2.046964   100
```

As mentioned, the results show similar runtimes but please share an example if you get different behavior.

**Comment by jasonjfoster** [comment]
Closing this issue now as the benchmarks have demonstrated nearly identical results. Please feel free to reopen if you get different behavior though.
